---
- name: Create /etc/kubernetes/pki Dir
  file:
    path: /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
    mode: '644'
    recurse: True

- name: Import all master components keys and certificates
  copy:
    src: "{{ pki_path }}/{{ item.src }}"
    dest: /etc/kubernetes/pki/{{ item.dest }}
  with_items:
    - { src: 'intermediate/ca.crt', dest: 'ca.crt' }
    - { src: 'end/kube-apiserver-kubelet-client.key', dest: 'apiserver-kubelet-client.key' }
    - { src: 'end/kube-apiserver-kubelet-client.crt', dest: 'apiserver-kubelet-client.crt' }
  notify:
    - restart kubelet
