---
- name: Folders creation /etc/kubernetes/pki /etc/kubernetes/pki/etcd
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '644'
  with_items:
    - /etc/kubernetes
    - /etc/kubernetes/pki

- name: Import kubernetes ca.crt
  copy:
    src: "{{ data_path }}/certificates/intermediate/kubernetes-ca/signed/kubernetes-ca.pem"
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '644'
  notify:
    - restart kubelet

- name: Import apiserver-kubelet-client.crt
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver-kubelet-client/kube-apiserver-kubelet-client.pem"
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.crt
    owner: root
    group: root
    mode: '644'
  notify:
    - restart kubelet

- name: Import apiserver-kubelet-client.key
  copy:
    src: "{{ data_path }}/certificates/end/kube-apiserver-kubelet-client/kube-apiserver-kubelet-client-key.pem"
    dest: /etc/kubernetes/pki/apiserver-kubelet-client.key
    owner: root
    group: root
    mode: '600'
  notify:
    - restart kubelet
