---
- name: Create /etc/kubernetes/pki Dir
  file:
    path: /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
    mode: '644'
    recurse: True

- name: Import master CA crt for kubelet
  copy:
    src: "{{ pki_path }}/intermediate/ca.crt"
    dest: /etc/kubernetes/pki/ca.crt
  with_items:
    - { src: 'intermediate/ca.crt', dest: 'ca.crt' }
  notify:
    - restart kubelet

- name: Import specific KEY for kubelet
  copy:
    src: "{{ pki_path }}/kubeconfigs/kubelet/{{ inventory_hostname }}/kubelet.key"
    dest: /etc/kubernetes/pki/kubelet.key
  notify:
    - restart kubelet

- name: Import specific KEY for kubelet
  copy:
    src: "{{ pki_path }}/kubeconfigs/kubelet/{{ inventory_hostname }}/kubelet.crt"
    dest: /etc/kubernetes/pki/kubelet.crt
  notify:
    - restart kubelet
