---
- name: Create /root/.kube directory
  file:
    path: /root/.kube
    state: directory
- name: Inject Kubeconfig
  copy:
    src: "{{ pki_path }}/kubeconfigs/admin/admin.conf"
    dest: /root/.kube/config