---
- name: Configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    create: yes
  with_items:
  - "{{ groups['all'] }}"
  when:
  - populate_etc_hosts
  - hostvars[item].ansible_host is defined
