---
- name: Delete intermediate CAs certs
  file:
    path: "{{ data_path }}certificates/intermediate/{{ item }}/signed/{{ item }}.pem"
    state: absent
  with_items:
    - kubernetes-front-proxy-ca
    - kubernetes-ca
    - etcd-ca

- name: Delete old END keys and associated certs
  file:
    path: "{{ data_path }}/certificates/end/"
    state: absent

- name: Delete old kubeconfig files
  file:
    path: "{{ data_path }}/certificates/configs/"
    state: absent
