---
- name: Install CFSSL
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.4.1/cfssl_1.4.1_linux_amd64
    dest: /usr/bin/cfssl
    mode: 0777
    owner: root
    group: root

- name: Install CFSSLJSON
  get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.4.1/cfssljson_1.4.1_linux_amd64
    dest: /usr/bin/cfssljson
    mode: 0777
    owner: root
    group: root
