---
- hosts: masters
  become: true
  tasks:
  - name: Stop API server
    service:
      name: kube-apiserver
      state: stopped
- hosts: etcd
  become: true
  roles:
    - restore-etcd
- hosts: masters
  become: true
  tasks:
  - name: Restart API server
    service:
      name: kube-apiserver
      state: started
