---
advertise_ip_masters: 1.2.3.4
kubernetes_service: 1.2.3.4

state_or_province_name: "Ile-De-France"
locality_name: "Paris"
country_name: "FR"
root_ca_common_name: "kubernetes"
expiry: "+3650d"
data_path: "/var/agorakube"
rotate_certificats: False
rotate_private_keys: False
rotate_token_certificats: False