---
- name: Create tempdir
  tempfile:
    state: directory
    suffix: calico
  register: calico_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ calico_tempdir.path }}/calico.yaml"
    src: "calico.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf apply -f {{ calico_tempdir.path }}/calico.yaml
  register: apply_calico
  changed_when: >
    apply_calico.stdout is search("created")
    or apply_calico.stdout is search("configured")

- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ calico_tempdir.path }}"
  changed_when: false

- name: Wait for Calico to be deployed
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf get deploy -n kube-system calico-kube-controllers
  changed_when: false
  register: calico_deployment
  until: calico_deployment.stdout.find("1/1") != -1
  retries: 300
  delay: 10
  run_once: true
