---
- name: Create tempdir
  tempfile:
    state: directory
    suffix: coredns
  register: coredns_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ coredns_tempdir.path }}/coredns.yaml"
    src: "coredns.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f {{ coredns_tempdir.path }}/coredns.yaml
  register: apply_coredns
  changed_when: >
    apply_coredns.stdout is search("created")
    or apply_coredns.stdout is search("configured")

- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ coredns_tempdir.path }}"
  changed_when: false

- name: Verify if coredns pods has successfully started
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf get deploy -n kube-system coredns
  changed_when: false
  register: dashboard_deployment
  until: dashboard_deployment.stdout.find("2/2") != -1
  retries: 300
  delay: 10
  run_once: true
