---
- name: Wait for nodes to be ready
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf get node {{ item }}
  changed_when: false
  register: node_deployment
  until: node_deployment.stdout.find("Ready") != -1
  retries: 300
  delay: 10
  run_once: true
  with_items: "{{ groups['all'] }}"
  when:
    - item not in groups['deploy']

- name: Label Woker Nodes
  command: "kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf label node {{ item }}  node-role.kubernetes.io/worker= --overwrite"
  changed_when: false
  with_items: "{{ groups['workers'] }}"

- name: Label Storage Nodes
  command: "kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf label node {{ item }} node-role.kubernetes.io/storage= --overwrite"
  changed_when: false
  with_items: "{{ groups['storage'] }}"

- name: Label Master Nodes
  command: "kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf label node {{ item }}  node-role.kubernetes.io/master= --overwrite"
  changed_when: false
  with_items: "{{ groups['masters'] }}"

- name: Make hosts with only master role NoSchedulabe
  command: |
    kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf \
    taint nodes {{ item }} node-role.kubernetes.io/master=true:NoSchedule --overwrite
  changed_when: false
  with_items: "{{ groups['masters'] }}"
  when:
    - item in groups['masters']
    - item not in groups['workers']
    - item not in groups['storage']
