---
- name: Include label workers
  include_tasks: label-workers.yaml

- name: Include Tasks Calico
  include_tasks: calico.yaml
  when: network_cni_plugin == 'calico'

- name: Include Tasks Kube-router
  include_tasks: kube-router.yaml
  when: network_cni_plugin == 'kube-router'

- name: Deploy CoreDNS to K8S
  include_tasks: coredns.yaml

- name: Install ingress (traefik)
  include_tasks: traefik.yaml
  when: ingress_controller == 'traefik'

- name: Install ingress (haproxy)
  include_tasks: haproxy.yaml
  when: ingress_controller == 'haproxy'

- name: Install ingress (nginx)
  include_tasks: nginx.yaml
  when: ingress_controller == 'nginx'

- name: Install MetalLB Layer2
  include_tasks: metallb_l2.yaml
  when: enable_metallb_layer2

- name: Install K8S Default Dashboard
  include_tasks: default_dashboard.yaml
  when: k8s_dashboard

- name: Install Metrics-Server
  include_tasks: metrics-server.yaml
  when: enable_metrics_server

- name: Install openebs for persistence
  include_tasks: openebs.yaml
  when: enable_persistence

- name: Install Monitoring
  include_tasks: monitoring.yaml
  when: enable_monitoring