---
- name: Create tempdir
  tempfile:
    state: directory
    suffix: traefik
  register: traefik_tempdir
  changed_when: false

- name: Render templates
  template:
    dest: "{{ traefik_tempdir.path }}/traefik.yaml"
    src: "traefik.yaml.j2"
  changed_when: false

- name: Apply templates
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf apply -f {{ traefik_tempdir.path }}/traefik.yaml
  register: apply_traefik
  changed_when: >
    apply_traefik.stdout is search("created")
    or apply_traefik.stdout is search("configured")

- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ traefik_tempdir.path }}"
  changed_when: false

- name: Verify if traefik-ingress-controller pods has successfully started
  command: kubectl --kubeconfig {{ pki_path }}/kubeconfigs/admin/admin.conf get deploy -n ingress-traefik traefik
  changed_when: false
  register: traefik_deployment
  until: traefik_deployment.stdout.find("1/1") != -1
  retries: 300
  delay: 10
  run_once: true
