---
- name: Folder creation /etc/kubernetes/pki /etc/kubernetes/pki/etcd
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '644'
    recurse: True
  with_items:
    - /etc/kubernetes/pki/etcd
    - /etc/kubernetes/pki/sa/backups

- name: Import all master components keys and certificates
  copy:
    src: "{{ pki_path }}/{{ item.src }}"
    dest: /etc/kubernetes/pki/{{ item.dest }}
  with_items:
    - { src: 'intermediate/etcd/ca.key', dest: 'etcd/ca.key' }
    - { src: 'intermediate/etcd/ca.crt', dest: 'etcd/ca.crt' }
    - { src: 'end/kube-apiserver-etcd-client.key', dest: 'apiserver-etcd-client.key' }
    - { src: 'end/kube-apiserver-etcd-client.crt', dest: 'apiserver-etcd-client.crt' }
    - { src: 'intermediate/ca.key', dest: 'ca.key' }
    - { src: 'intermediate/ca.crt', dest: 'ca.crt' }
    - { src: 'end/kube-apiserver.key', dest: 'apiserver.key' }
    - { src: 'end/kube-apiserver.crt', dest: 'apiserver.crt' }
    - { src: 'end/kube-apiserver-kubelet-client.key', dest: 'apiserver-kubelet-client.key' }
    - { src: 'end/kube-apiserver-kubelet-client.crt', dest: 'apiserver-kubelet-client.crt' }
    - { src: 'intermediate/front-proxy-ca.key', dest: 'front-proxy-ca.key' }
    - { src: 'intermediate/front-proxy-ca.crt', dest: 'front-proxy-ca.crt' }
    - { src: 'end/front-proxy-client.key', dest: 'front-proxy-client.key' }
    - { src: 'end/front-proxy-client.crt', dest: 'front-proxy-client.crt' }
  notify:
    - Restart kube-apiserver service
    - Restart kube-scheduler service
    - Restart kube-controller-manager service

- name: Import SA private keys and public key used for Token authentication
  copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki/sa/
  with_fileglob:
    - "{{ pki_path  }}/sa/*"
  notify:
    - Restart kube-apiserver service
    - Restart kube-scheduler service
    - Restart kube-controller-manager service

#- name: Import new token authentication key
#  copy:
#    src: "{{ item }}"
#    dest: /etc/kubernetes/pki/token_authentication_keys/
#    owner: root
#    group: root
#    mode: '600'
#  with_fileglob:
#    - "{{ data_path }}/authentication_keys/*"
